### ISSUE TITLE
Support other languages.

### ISSUE THREAD

**Issue by 201341** [generalui/s3p#59] opened 2021-12-24 09:02 UTC
If we extend the `supportKeychar` to all ascii code, so can s3p support other language?

**Comment by 201341** [comment] 2021-12-24 10:01
> If we extend the `supportKeychar` to all ascii code, can s3p  support other language?

**Comment by shanebdavis** [comment] 2022-03-03 21:15
Duplicate of #60

**Closed by shanebdavis** 2022-03-03 21:15 UTC
